In [16]:
#Independence
import pandas as pd
from scipy import stats
import scipy

In [5]:
df=pd.read_csv("C:/Users/Asus/Downloads/chi1__2__lyst1729241145055 (1).csv")

In [6]:
df

     age intervals Experience intervals
0          41 - 50         6 - 10 Years
1          41 - 50         6 - 10 Years
2          31 - 40         6 - 10 Years
3          31 - 40         6 - 10 Years
4          18 - 30         6 - 10 Years
...            ...                  ...
1465       31 - 40        11 - 20 Years
1466       31 - 40         6 - 10 Years
1467       18 - 30         6 - 10 Years
1468       41 - 50        11 - 20 Years
1469       31 - 40         6 - 10 Years

[1470 rows x 2 columns]

___INDEPENDENCE:-
we will judge the columns are independent or seprate.

In [7]:
df.dtypes

age intervals           object
Experience intervals    object
dtype: object

In [9]:
df["age intervals"].value_counts()

age intervals
31 - 40    619
18 - 30    386
41 - 50    322
51 - 60    143
Name: count, dtype: int64

In [10]:
df["Experience intervals"].value_counts()

Experience intervals
6 - 10 Years     607
11 - 20 Years    340
Upto 5 Years     316
21 - 40 Years    207
Name: count, dtype: int64

In [13]:

ct=pd.crosstab(df["age intervals"],df["Experience intervals"],margins=True)

In [14]:
ct

Experience intervals,11 - 20 Years,21 - 40 Years,6 - 10 Years,Upto 5 Years,All
age intervals,,,,,
18 - 30,22,0,172,192,386
31 - 40,190,20,308,101,619
41 - 50,85,112,110,15,322
51 - 60,43,75,17,8,143
All,340,207,607,316,1470

In [18]:
#finding chi square for above table
chi2,p,dof,expected=scipy.stats.chi2_contingency(ct)

In [28]:
#chi2 value
#original value of chi
chi2

np.float64(679.971444973354)

In [23]:
#significance level variable
p

np.float64(2.359819766769466e-134)

In [24]:
#degree of freedom
dof

16

In [25]:
#expected value 
expected

array([[  89.27891156,   54.35510204,  159.38911565,   82.97687075,
         386.        ],
       [ 143.17006803,   87.16530612,  255.60068027,  133.06394558,
         619.        ],
       [  74.47619048,   45.34285714,  132.96190476,   69.21904762,
         322.        ],
       [  33.07482993,   20.13673469,   59.04829932,   30.74013605,
         143.        ],
       [ 340.        ,  207.        ,  607.        ,  316.        ,
        1470.        ]])

In [27]:
# calculated value oh chi
chi1=26.296

ho---> age interval have relationship with the experience interval.
h1---> have no relationship with the experience.

we will reject the null hypothesis as the calculated value is greater then the orignial chi value .

__GOODNESS OF FIT:-
this helps us to find the equal propertion in different section of the feature.

In [29]:
expected_list=[50,50,50,50,50]
observed_list=[50,60,40,47,53]

In [31]:
sum(observed_list)

250

In [32]:
sum(expected_list)

250

In [33]:
stats.chisquare(f_obs=observed_list,f_exp=expected_list)

Power_divergenceResult(statistic=np.float64(4.359999999999999), pvalue=np.float64(0.3594720674366307))

ho-->claim is false.
h1-->claim is true.

we will reject the null hypothesis as we dont have enough evidence.